title: "Building AI-Assisted Operations: Agentic AI Workshop"
author: Engin Diri

markdown: kramdown

kramdown:
  input: GFM

plugins:
- jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include:
- 00-introduction.md
- 01-create-kubernetes-cluster.md
- 02-deploy-kagent-mcp.md
- 03-deploy-platform-workload.md
- 04-multi-agent-troubleshooting.md
- 05-housekeeping.md
